# Generated by Django 3.1.7 on 2021-04-20 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Маклер',
                'verbose_name_plural': 'Маклеры',
            },
        ),
        migrations.CreateModel(
            name='PlayerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100, verbose_name='Никнейм')),
                ('role', models.CharField(choices=[('unassigned', 'Не назначена'), ('producer', 'Производитель'), ('broker', 'Маклер')], default='unassigned', max_length=20, verbose_name='Игровая роль')),
                ('role_name', models.CharField(default='unassigned', max_length=20, verbose_name='Игровое имя')),
                ('position', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Место')),
                ('ended_turn', models.BooleanField(default=False)),
                ('city', models.CharField(choices=[('unassigned', 'Не назначен'), ('IV', 'Айво'), ('WS', 'Вемшир'), ('TT', 'Тортуга'), ('AD', 'Алендор'), ('NF', 'Неверфол'), ('ET', 'Этруа')], default='unassigned', max_length=20, verbose_name='Расположение')),
                ('balance', models.IntegerField(default=0)),
                ('is_bankrupt', models.BooleanField(default=False)),
                ('status', models.CharField(default='OK', editable=False, max_length=20, verbose_name='Статус банкротства')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
            },
        ),
        migrations.CreateModel(
            name='ProducerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billets_produced', models.IntegerField(default=0)),
                ('billets_stored', models.IntegerField(default=0)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='producer', to='game.playermodel')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.CreateModel(
            name='SessionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('game_type', models.CharField(choices=[('normal', 'Стандартная'), ('hard', 'Сложная')], default='normal', max_length=15, verbose_name='Тип игры')),
                ('turn_count', models.PositiveSmallIntegerField(verbose_name='Число ходов')),
                ('number_of_brokers', models.PositiveSmallIntegerField(default=0, verbose_name='Число маклеров')),
                ('crown_balance', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Баланс Короны')),
                ('status', models.CharField(choices=[('initialized', 'Сессия инициализирована'), ('started', 'Сессия запущена'), ('finished', 'Сессия закончилась')], default='initialized', editable=False, max_length=15, verbose_name='Статус')),
                ('broker_starting_balance', models.PositiveSmallIntegerField(default=0, verbose_name='Баланс \n маклера')),
                ('producer_starting_balance', models.PositiveSmallIntegerField(default=0, verbose_name='Баланс производителя')),
                ('transaction_limit', models.PositiveSmallIntegerField(default=2000, editable=False)),
                ('current_turn', models.PositiveSmallIntegerField(default=0, verbose_name='Текущий ход')),
                ('turn_phase', models.CharField(choices=[('negotiation', 'Этап переговоров'), ('transaction', 'Этап заключения сделок')], default='negotiation', max_length=20, verbose_name='Фаза хода')),
                ('allow_show_balance', models.BooleanField(default=False, verbose_name='Разрешить производителям показывать баланс')),
                ('allow_show_transacton_sum', models.BooleanField(default=False, verbose_name='Показывать маклерам сумму транзакций')),
            ],
            options={
                'verbose_name': 'Сессия',
                'verbose_name_plural': 'Сессии',
            },
        ),
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('price', models.PositiveSmallIntegerField(default=0)),
                ('transporting_cost', models.PositiveSmallIntegerField(default=10, editable=False)),
                ('turn', models.PositiveSmallIntegerField(editable=False)),
                ('status', models.CharField(choices=[('active', 'Сделка на рассмотрении'), ('accepted', 'Сделка согласована'), ('denied', 'Сделка отклонена')], default='active', max_length=15)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='game.brokermodel')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='game.producermodel')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='game.sessionmodel')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
            },
        ),
        migrations.AddField(
            model_name='playermodel',
            name='session',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='player', to='game.sessionmodel', verbose_name='Сессия'),
        ),
        migrations.AddField(
            model_name='brokermodel',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='broker', to='game.playermodel'),
        ),
        migrations.CreateModel(
            name='BalanceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_turn_balance', models.IntegerField(default=0)),
                ('end_turn_balance', models.IntegerField(default=0)),
                ('sales_income', models.IntegerField(default=0)),
                ('fixed_costs', models.IntegerField(default=0)),
                ('variable_costs', models.IntegerField(default=0)),
                ('raw_stuff_costs', models.IntegerField(default=0)),
                ('fine', models.IntegerField(default=0)),
                ('storage', models.IntegerField(default=0)),
                ('logistics', models.IntegerField(default=0)),
                ('purchase_blanks', models.IntegerField(default=0)),
                ('blanks', models.IntegerField(default=0)),
                ('crown', models.IntegerField(default=0)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='game.playermodel')),
            ],
        ),
    ]
