# Generated by Django 3.1.7 on 2021-04-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionmodel',
            name='allow_show_balance',
            field=models.BooleanField(default=False, verbose_name='Разрешить показывать баланс'),
        ),
        migrations.AddField(
            model_name='sessionmodel',
            name='allow_show_transacton_sum',
            field=models.BooleanField(default=False, verbose_name='Разрешить показывать сумму транзакций'),
        ),
        migrations.AlterField(
            model_name='sessionmodel',
            name='broker_starting_balance',
            field=models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Баланс \n маклера'),
        ),
        migrations.AlterField(
            model_name='sessionmodel',
            name='crown_balance',
            field=models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Баланс Короны'),
        ),
        migrations.AlterField(
            model_name='sessionmodel',
            name='game_type',
            field=models.CharField(choices=[('normal', 'Стандартная'), ('hard', 'Сложная')], default='normal', max_length=15, verbose_name='Тип игры'),
        ),
        migrations.AlterField(
            model_name='sessionmodel',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='sessionmodel',
            name='number_of_brokers',
            field=models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Число маклеров'),
        ),
        migrations.AlterField(
            model_name='sessionmodel',
            name='producer_starting_balance',
            field=models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Баланс производителя'),
        ),
        migrations.AlterField(
            model_name='sessionmodel',
            name='status',
            field=models.CharField(choices=[('initialized', 'Сессия инициализирована'), ('started', 'Сессия запущена'), ('finished', 'Сессия закончилась')], default='initialized', max_length=15, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='sessionmodel',
            name='turn_count',
            field=models.PositiveSmallIntegerField(verbose_name='Число ходов'),
        ),
        migrations.AlterField(
            model_name='sessionmodel',
            name='turn_phase',
            field=models.CharField(choices=[('negotiation', 'Этап переговоров'), ('transaction', 'Этап заключения сделок')], default='negotiation', max_length=20, verbose_name='Фаза хода'),
        ),
    ]
