# Generated by Django 3.1.7 on 2021-04-14 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_playermodel_role_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn', models.PositiveSmallIntegerField(default=0)),
                ('data', models.CharField(max_length=200)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='game.playermodel')),
            ],
        ),
    ]
