# Generated by Django 3.1.7 on 2021-04-15 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_remove_balancedetail_turn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancedetail',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='game.playermodel'),
        ),
    ]
