# Generated by Django 3.1.7 on 2021-04-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20210415_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balancedetail',
            name='data',
        ),
        migrations.AddField(
            model_name='balancedetail',
            name='end_turn_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='balancedetail',
            name='fine',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='balancedetail',
            name='fixed_costs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='balancedetail',
            name='logistics',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='balancedetail',
            name='raw_stuff_costs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='balancedetail',
            name='sales_income',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='balancedetail',
            name='start_turn_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='balancedetail',
            name='storage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='balancedetail',
            name='variable_costs',
            field=models.IntegerField(default=0),
        ),
    ]
